steps:
# Setup SSH
# These are required before dep
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=ci/id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=build
  - --key=build-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'get-ssh-key'
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv ./ci/github_known_hosts /root/.ssh/known_hosts
    git config --global url."ssh://git@github.com/solo-io".insteadOf https://github.com/solo-io
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'configure-git'

# Can create a dep cache by running 'gcloud builds submit . --config=cloudbuild-cache.yaml'
# These two steps should populate the cache
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p ./gopath/pkg/dep && gsutil cat gs://gloo-ee-cache/service-mesh-hub/service-mesh-hub-dep.tar.gz | tar -xzf -']
  id: 'download-untar-dep-cache'

# Run dep to set up the project so it can be built and tested
# Dep modifies workspace so that the code is moved into the PROJECT_ROOT
# All steps after this must set GOPATH
- name: 'gcr.io/$PROJECT_ID/dep:0.1.8'
  args: ['ensure']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/service-mesh-hub'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'dep'
  waitFor: ['download-untar-dep-cache', 'configure-git']

- name: 'gcr.io/$PROJECT_ID/ginkgo:0.1.8'
  env:
  - 'PROJECT_ROOT=github.com/solo-io/service-mesh-hub'
  - 'GOPATH=/workspace/gopath'
  dir: './gopath/src/github.com/solo-io/service-mesh-hub'
  args: ['-r', '-p', '-failFast', '-race']
  secretEnv: ['GITHUB_TOKEN']
  waitFor: ['dep']
  id: 'test'

secrets:
- kmsKeyName: projects/gloo-ee/locations/global/keyRings/build/cryptoKeys/build-key
  secretEnv:
    GITHUB_TOKEN: CiQAwdWthrSJ1uI5Ao/LnmX8OzXmA5TNCtDpeV6JdNouaGh5vpwSUQD5SXFIkCBvnu/wYDSGwgWNJaQV75wP/kDephn5GGuGCe0EGFXXE54zyH8iHRL45Uq0s39SoHEyYoZXF2Qla8IbKGAKswPRViYSChPthQILdA==

timeout: 3000s
tags: ['service-mesh-hub']
options:
  machineType: 'N1_HIGHCPU_32'
